### ISSUE TITLE
`installer.install(localPath, ...)` is a thinly veiled `fs.copy`

### ISSUE THREAD

**Issue by eric-wieser** [cc-scripts/cc-scripts#12]
Do we need this variant at all?

**Comment by damien** [comment]
When I wrote `installer` I was just thinking of it as a more general purpose implementation of `fs.copy`; one that could handle both remote and local files.

Did you find the `installer.install` behavior confusing? If so that probably means I either need to improve whatever documentation I have for it, rename it to something less confusing, or both.

**Comment by eric-wieser** [comment]
I've just made a commit that removes it completely. It'll be here in a moment...
